#!/bin/sh

BASEDIR=$(cd `dirname $0`; pwd)
DOWNLOADROOT=${BASEDIR}/../../../../dl
OUTPUTROOT=${BASEDIR}/../../../../output
BUILDROOT=${BASEDIR}/../../../../build

source ${BASEDIR}/env.sh

TARBALL=Python-${BASE_VERSION}.tgz

cd ${DOWNLOADROOT}
if [ -f ${TARBALL} ];then
    echo ${TARBALL}" exists, stop downloading"
else
    echo ${TARBALL}" not exists, downloading"
    wget ${DLURL}/${BASE_VERSION}/${TARBALL}
fi
tar zxf ${TARBALL}
mv Python-${BASE_VERSION} ${BUILDROOT}/

cd ${BUILDROOT}/Python-${BASE_VERSION}/
./configure --prefix=${CONFIG_PREFIX} --enable-optimizations
make -j4
sudo make install

#if [ ! -f /usr/lib64/libpython3.6m.so ]; then
#    sudo ln -sf ${CONFIG_PREFIX}/lib/libpython3.6m.so /usr/lib64/
#fi
#if [ ! -f /usr/lib64/libpython3.6m.so.1.0 ]; then
#    sudo ln -sf ${CONFIG_PREFIX}/lib/libpython3.6m.so.1.0 /usr/lib64/
#fi

cd ${CONFIG_PREFIX}/bin
./pip3 install --upgrade pip setuptools

if [[ ${OS_RELEASE} == 'centos' || ${OS_RELEASE} == 'redhat' ]]; then
    source ${BASEDIR}/./centos/${OS_VERSION}/*
elif [[ ${OS_RELEASE} == 'ubuntu' ]]; then
    source ${BASEDIR}/./ubuntu/${OS_CODENAME}/*
fi

