#!/bin/sh

BASEDIR=$(cd `dirname $0`; pwd)
DOWNLOADROOT=${BASEDIR}/../../../../dl
OUTPUTROOT=${BASEDIR}/../../../../output
BUILDROOT=${BASEDIR}/../../../../build
VERSION=3.6.4
TARBALL=Python-${VERSION}.tgz

cd ${DOWNLOADROOT}
if [ -f ${TARBALL} ];then
    echo ${TARBALL}" exists, stop downloading"
else
    echo ${TARBALL}" not exists, downloading"
    wget https://www.python.org/ftp/python/${VERSION}/${TARBALL}
fi
tar zxf ${TARBALL}
mv Python-${VERSION} ${BUILDROOT}/python3

cd ${BUILDROOT}/python3/
./configure --prefix=/usr/lib/pylearning3
sudo make -j4 install
cd /usr/lib/pylearning3/bin
sudo ./pip3 install --upgrade setuptools pip
sudo ./pip3 install awscli

