#!/bin/sh

BASEDIR=$(cd `dirname $0`; pwd)
DOWNLOADROOT=${BASEDIR}/../../../../dl
OUTPUTROOT=${BASEDIR}/../../../../output
BUILDROOT=${BASEDIR}/../../../../build

cd ${DOWNLOADROOT}
wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz
tar zxf Python-3.6.4.tgz
mv Python-3.6.4 ${BUILDROOT}/python3

cd ${BUILDROOT}/python3/
./configure --prefix=/usr/lib/pylearning3
sudo make -j4 install
cd /usr/lib/pylearning3/bin
sudo ./pip install --upgrade setuptools pip
sudo ./pip install awscli

