#!/bin/sh

BASEDIR=$(cd `dirname $0`; pwd)
DOWNLOADROOT=${BASEDIR}/../../../../dl
OUTPUTROOT=${BASEDIR}/../../../../output
BUILDROOT=${BASEDIR}/../../../../build

source ${BASEDIR}/env.sh

sudo rm -rf /usr/lib/pylearning3
#sudo rm -f /usr/lib64/libpython3.6m.so
#sudo rm -f /usr/lib64/libpython3.6m.so.1.0
sudo rm -rf ${BUILDROOT}/Python-${BASE_VERSION}