#!/bin/sh

BASEDIR=$(cd `dirname $0`; pwd)
DOWNLOADROOT=${BASEDIR}/../../../../dl
OUTPUTROOT=${BASEDIR}/../../../../output
BUILDROOT=${BASEDIR}/../../../../build

source ${BASEDIR}/env.sh

sudo rm -rf /usr/lib/pylearning2
#if [ -f /usr/lib64/libpython2.7.so ]; then
#    if [ -L /usr/lib64/libpython2.7.so ]; then
#        sudo rm -f /usr/lib64/libpython2.7.so
#    fi
#fi
#if [ -f /usr/lib64/libpython2.7.so.1.0 ]; then
#    if [ -L /usr/lib64/libpython2.7.so.1.0 ]; then
#        sudo rm -f /usr/lib64/libpython2.7.so.1.0
#    fi
#fi
sudo rm -rf ${BUILDROOT}/Python-${BASE_VERSION}