#!/bin/sh

BASEDIR=$(cd `dirname $0`; pwd)
DOWNLOADROOT=${BASEDIR}/../../../../dl
OUTPUTROOT=${BASEDIR}/../../../../output
BUILDROOT=${BASEDIR}/../../../../build

sudo rm -rf /usr/lib/pylearning2
sudo rm -f /usr/lib64/libpython2.7.so
sudo rm -f /usr/lib64/libpython2.7.so.1.0
# sudo rm -rf ${BUILDROOT}/python2