#!/usr/bin/env python
# coding: utf-8
# author: xianglei, 2018

from Modules.building import Builder
import sys

builder = Builder()

if '__main__' == __name__:
    if not sys.argv[1]:
        print 'Usage: ./tent component'
        print 'Available components:'
        print '     pylearning2'
        print '     pylearning3'
    else:
        component = sys.argv[1]
        builder.do_package(component)











