#!/bin/sh

sudo ./pip install requests
sudo ./pip install six
sudo ./pip install numpy
sudo ./pip install h5py
sudo ./pip install cython
sudo ./pip install automl
sudo ./pip install bigml
sudo ./pip install beautifulsoup4
sudo ./pip install opencv-python
sudo ./pip install graphviz
sudo ./pip install gensim
sudo ./pip install Geohash
sudo ./pip install gym
sudo ./pip install jieba
sudo ./pip install keras
sudo ./pip install matplotlib
sudo ./pip install mlpy
sudo ./pip install networkx
sudo ./pip install nltk
sudo ./pip install pandas
sudo ./pip install pandas2sklearn
sudo ./pip install git+https://github.com/clips/pattern@development#egg=pattern
sudo ./pip install python-geohash
sudo ./pip install python-crfsuite
sudo ./pip install pyspark
sudo ./pip install scipy
sudo ./pip install seaborn
sudo ./pip install sklearn
sudo ./pip install sklearn-crfsuite
sudo ./pip install sklearn-pandas
sudo ./pip install snownlp
sudo ./pip install spark-sklearn
sudo ./pip install statsmodels
sudo ./pip install theano
sudo ./pip install xgboost
sudo ./pip install opencv-contrib-python
sudo ./pip install pyspark-hbase
sudo ./pip install tensorflow
sudo ./pip install mxnet
sudo ./pip install tensorboard
sudo ./pip install scrapy
sudo ./pip install virtualenv
sudo ./pip install aerospike
sudo ./pip install amqp
sudo ./pip install apscheduler
sudo ./pip install avro
sudo ./pip install awscli
sudo ./pip install cassandra-driver
sudo ./pip install celery
sudo ./pip install cx_oracle
sudo ./pip install easybase
sudo ./pip install elasticsearch
sudo ./pip install fabric
sudo ./pip install freeze
sudo ./pip install gevent
sudo ./pip install greelet
sudo ./pip install python-gssapi
sudo ./pip install hbase-thrift
sudo ./pip install hive-thrift-py
sudo ./pip install kafka
sudo ./pip install kazoo
sudo ./pip install kerberos
sudo ./pip install kombu
sudo ./pip install log4python
sudo ./pip install mrjob
sudo ./pip install pandas-oracle
sudo ./pip install paramiko
sudo ./pip install parquet
sudo ./pip install pika
sudo ./pip install protobuf
sudo ./pip install py4j
sudo ./pip install pyaml
sudo ./pip install pyinstaller
sudo ./pip install pymongo
sudo ./pip install pymssql
sudo ./pip install pymysql
sudo ./pip install python-cassandra
sudo ./pip install python-memcached
sudo ./pip install python-snappy
sudo ./pip install redis
sudo ./pip install django==1.11
sudo ./pip install flask
sudo ./pip install simplejson
sudo ./pip install tabulate
sudo ./pip install teradata
sudo ./pip install thrift
sudo ./pip install thriftpy
sudo ./pip install tornado
sudo ./pip install tqdm
sudo ./pip install XlsxWriter
sudo ./pip install PyStemmer
sudo ./pip install python-lzo
sudo ./pip install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp27-cp27mu-linux_x86_64.whl
sudo ./pip install torchvision
sudo ./pip install word2vec
sudo ./pip install fasttext
sudo ./pip install lightgbm
sudo ./pip install future
sudo ./pip install futures