#!/bin/sh

sudo ./pip3 install --upgrade setuptools pip
sudo ./pip3 install requests
sudo ./pip3 install six
sudo ./pip3 install numpy
sudo ./pip3 install h5py
sudo ./pip3 install cython
sudo ./pip3 install git+https://github.com/clips/pattern@development#egg=pattern
sudo ./pip3 install automl
sudo ./pip3 install beautifulsoup4
sudo ./pip3 install bigml
sudo ./pip3 install opencv-python
sudo ./pip3 install graphviz
sudo ./pip3 install gensim
sudo ./pip3 install Geohash
sudo ./pip3 install gym
sudo ./pip3 install jieba
sudo ./pip3 install keras
sudo ./pip3 install matplotlib
sudo ./pip3 install networkx
sudo ./pip3 install nltk
sudo ./pip3 install pandas
sudo ./pip3 install pandas2sklearn
sudo ./pip3 install python-geohash
sudo ./pip3 install python-crfsuite
sudo ./pip3 install pyspark
sudo ./pip3 install scipy
sudo ./pip3 install seaborn
sudo ./pip3 install sklearn
sudo ./pip3 install sklearn-crfsuite
sudo ./pip3 install sklearn-pandas
sudo ./pip3 install snownlp
sudo ./pip3 install spark-sklearn
sudo ./pip3 install statsmodels
sudo ./pip3 install theano
sudo ./pip3 install xgboost
sudo ./pip3 install opencv-contrib-python
sudo ./pip3 install pyspark-hbase
sudo ./pip3 install tensorflow
sudo ./pip3 install mxnet
sudo ./pip3 install tensorboard
sudo ./pip3 install scrapy
sudo ./pip3 install virtualenv
sudo ./pip3 install aerospike
sudo ./pip3 install amqp
sudo ./pip3 install apscheduler
sudo ./pip3 install avro
sudo ./pip3 install awscli
sudo ./pip3 install cassandra-driver
sudo ./pip3 install celery
sudo ./pip3 install cx_oracle
sudo ./pip3 install easybase
sudo ./pip3 install elasticsearch
sudo ./pip3 install fabric
sudo ./pip3 install freeze
sudo ./pip3 install gevent
sudo ./pip3 install greenlet
sudo ./pip3 install python-gssapi
sudo ./pip3 install hbase-thrift
sudo ./pip3 install hive-thrift-py
sudo ./pip3 install kafka
sudo ./pip3 install kazoo
sudo ./pip3 install kerberos
sudo ./pip3 install kombu
sudo ./pip3 install log4python
sudo ./pip3 install mrjob
sudo ./pip3 install pandas-oracle
sudo ./pip3 install paramiko
sudo ./pip3 install parquet
sudo ./pip3 install pattern
sudo ./pip3 install pika
sudo ./pip3 install protobuf
sudo ./pip3 install py4j
sudo ./pip3 install python-geohash
sudo ./pip3 install pyaml
sudo ./pip3 install python-crfsuite
sudo ./pip3 install pyinstaller
sudo ./pip3 install pymongo
sudo ./pip3 install pymssql
sudo ./pip3 install pymysql
sudo ./pip3 install pyspark
sudo ./pip3 install python-cassandra
sudo ./pip3 install python-memcached
sudo ./pip3 install python-snappy
sudo ./pip3 install redis
sudo ./pip3 install django
sudo ./pip3 install flask
sudo ./pip3 install scipy
sudo ./pip3 install seaborn
sudo ./pip3 install simplejson
sudo ./pip3 install sklearn
sudo ./pip3 install sklearn-crfsuite
sudo ./pip3 install sklearn-pandas
sudo ./pip3 install snownlp
sudo ./pip3 install spark-sklearn
sudo ./pip3 install statsmodels
sudo ./pip3 install tabulate
sudo ./pip3 install teradata
sudo ./pip3 install theano
sudo ./pip3 install thrift
sudo ./pip3 install thriftpy
sudo ./pip3 install tornado
sudo ./pip3 install tqdm
sudo ./pip3 install XlsxWriter
sudo ./pip3 install PyStemmer
sudo ./pip3 install python-lzo
sudo ./pip3 install lzo-indexer
sudo ./pip3 install http://download.pytorch.org/whl/cpu/torch-0.3.1-cp36-cp36m-linux_x86_64.whl
sudo ./pip3 install torchvision
sudo ./pip3 install word2vec
sudo ./pip3 install fasttext
sudo ./pip3 install lightgbm
sudo ./pip3 install future
sudo ./pip3 install futures